import { Inter } from 'next/font/google'
import './globals.css'
import { InquiryForm } from '@/(components)'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Evana Infratech',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}
        <InquiryForm/>
      </body>
    </html>
  )
}
